BookStore/Areas/Admin/Controllers/CategoryController.cs
using DataAccess.Data;
using DataAccess.Repository;
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models.Entites;
using Utilites;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles =StaticDetails.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _UnitOfWork = unitOfWork;

        }
        public IActionResult Index()
        {
            List<Category> categories = _UnitOfWork.Category.GetAll().ToList();
            return View(categories);
        }
        public IActionResult Create()
        {
            return View();

        }

        [HttpPost]
        public IActionResult Create(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "Category Name and Display Order Cannot be exactly same");
            }
            if (ModelState.IsValid)
            {
                TempData["Success"] = "Category Created Succeccfully";
                _UnitOfWork.Category.Add(obj);
                _UnitOfWork.Save();
            }
            return RedirectToAction("Index");

        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? CategoryFromDb = _UnitOfWork.Category.Get(temp => temp.ID == id);
            if (CategoryFromDb == null)
            {
                return NotFound();
            }
            return View(CategoryFromDb);
        }
        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _UnitOfWork.Category.Update(category);
                _UnitOfWork.Save();
                TempData["Success"] = "Category Edited Succeccfully";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? CategoryFromDb = _UnitOfWork.Category.Get(temp => temp.ID == id);
            if (CategoryFromDb == null)
            {
                return NotFound();
            }
            return View(CategoryFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Category? obj = _UnitOfWork.Category.Get(temp => temp.ID == id);
            if (obj == null)
            {
                return NotFound();
            }

            _UnitOfWork.Category.Delete(obj);
            _UnitOfWork.Save();
            TempData["Success"] = "Category Deleted Succeccfully";
            return RedirectToAction("index");
        }
    }
}

BookStore/Areas/Admin/Controllers/ProductsController.cs
using DataAccess.Repository;
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.FileProviders;
using Models.Entites;
using Models.ViewModels;
using Utilites;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles = StaticDetails.Role_Admin)]
    public class ProductsController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        private readonly IWebHostEnvironment _WebHostEnvironment;
        public ProductsController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _UnitOfWork = unitOfWork;
            _WebHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var ProductsList = _UnitOfWork.Product.GetAll(includeProperties: nameof(Product.Category));
            return View(ProductsList);
        }
        public IActionResult Upsert(int? id)
        {
            
            ProductVM productVM = new ProductVM()
            {
                CategoryList = _UnitOfWork.Category.GetAll().Select(
               temp => new SelectListItem { Text = temp.Name, Value = temp.ID.ToString() }
              ),
                product = new Product()

            };

            if (id == null||id==0)
            {
                return View(productVM);
            }
            else
            {
                productVM.product = _UnitOfWork.Product.Get(temp => temp.ID == id);
                return View(productVM);
            }
            
        }

        [HttpPost]
        public IActionResult Upsert(ProductVM productVM,IFormFile? file)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            
            //place of wwwroot on machine like for example C:\Projects\MyApp
            string wwwRootPath = _WebHostEnvironment.WebRootPath;
            if (file != null)
            {
                //creates a random guid as a name for the file and append the extension 
                //of the file we got from form at the end of the guid
              
                string FileName=Guid.NewGuid().ToString() +Path.GetExtension(file.FileName);

                //it combines the root folder path on machine and the path of folder you mention
                //for example return will be C:\Projects\MyApp\wwwroot\images\product
                string ProductPath =Path.Combine(wwwRootPath,@"images\product");

                if (!string.IsNullOrEmpty(productVM.product.ImageUrl))
                {
                    var OldImagePath = Path.Combine(wwwRootPath, productVM.product.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(OldImagePath))
                    {
                        System.IO.File.Delete(OldImagePath);
                    }
                }
                using (var FileStream = new FileStream(Path.Combine(ProductPath, FileName), FileMode.Create))
                {
                    file.CopyTo(FileStream);
                }
                productVM.product.ImageUrl = @"\Images\Product\" + FileName;
            }
            if (productVM.product.ID == 0 || productVM.product == null)
            {
                TempData["Success"] = "Product Added Succeccfully";
                _UnitOfWork.Product.Add(productVM.product);
            }
            else
            {
                TempData["Success"] = "Product Updated Succeccfully";
                _UnitOfWork.Product.Update(productVM.product);
            }
        
        
            _UnitOfWork.Save();
            return RedirectToAction("Index");

        }



        //public IActionResult Delete(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }
        //    Product? obj = _UnitOfWork.Product.Get(temp => temp.ID == id);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(obj);
        //}
        //[HttpPost, ActionName("Delete")]
        //public IActionResult DeleteProduct(int? id)
        //{
        //    Product? obj = _UnitOfWork.Product.Get(temp => temp.ID == id);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }
        //    _UnitOfWork.Product.Delete(obj);
        //    _UnitOfWork.Save();
        //    TempData["Success"] = "Category Deleted Succeccfully";
        //    return RedirectToAction("Index");
        //}
        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            var ProductsList=_UnitOfWork.Product.GetAll(includeProperties: nameof(Product.Category));
            return Json(new { data = ProductsList });
        }
       
        public IActionResult Delete(int? id)
        {
            var ProdectToDelete = _UnitOfWork.Product.Get(temp=>temp.ID==id);
            if (ProdectToDelete == null)
            {
                return Json(new { success = false, message = "Error While Deleting" });
            }
            var OldImagePath = Path.Combine(_WebHostEnvironment.WebRootPath, ProdectToDelete.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(OldImagePath))
            {
                System.IO.File.Delete(OldImagePath);
            }
            _UnitOfWork.Product.Delete(ProdectToDelete);
            _UnitOfWork.Save();
            return Json(new { success=true, message="Delete Successful" });
        }

        #endregion
    }
}

BookStore/Areas/Admin/Views/Category/Delete.cshtml
@model Category
<div class="card shadow border-0 mt-4">
	<div class="cardaccordion-header bg-secondary bg-gradient m-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Delete Category</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<form method="post">
			<input asp-for="ID" hidden />
			<div class=" border p-3 mt-4">
				
				<div class="mb-3 row p-1">
					<label asp-for="Name" class="p-0">Category Name</label>
					<input asp-for="Name" class="form-control" disabled />

				</div>
				<div class="mb-3 row p-1">
					<label asp-for="DisplayOrder" class="p-0">Display Order</label>
					<input asp-for="DisplayOrder" class="form-control" disabled />

				</div>
				<div class="row">
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-danger form-control">Delete</button>
					</div>
					<div class="col-6  col-md-3">
						<a asp-controller="Category" asp-action="Index" class="btn btn-success  form-control">Back to Category List</a>
					</div>
				</div>

			</div>

		</form>
	</div>
</div>

BookStore/Areas/Admin/Views/Category/Edit.cshtml
@model Category
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Edit Category</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="ID" hidden />
            <div class="border p-3 mt-4">
                @*<div asp-validation-summary="ModelOnly"></div>*@
               <div class="form-floating py-2 col-12">
                    <input asp-for="Name" class="form-control border-0 shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DisplayOrder" class="form-control border-0 shadow" />
                    <label asp-for="DisplayOrder" class="ms-2"></label>
                    <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                </div>

                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Update</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary border  form-control">
                            Back to List
                        </a>
                    </div>
                </div>


            </div>
        </form>
    </div>
</div>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BookStore/Areas/Admin/Views/Category/Index.cshtml
@model List<Category>
<div class="container">
	<div class="row pt-4 pb-3">
		<div class="col-6">
			<h2 class="text-primary">
				Category List
			</h2>
		</div>
		<div class="col-6 text-end">
			<a asp-controller="Category" asp-action="Create" class="btn btn-primary">
				<i class="bi bi-plus-circle "></i> Create New Category
		  </a>
		</div>
	</div>
	
<table class="table table-bordered table-striped">
	<thead>

	<tr>
		<th>
			Category Name
		</th>
		<th>
			Display Order
		</th>
		<th>
			
		</th>

	</tr>
	</thead>
	<tbody>
		@foreach(var Category in Model.OrderBy(s=>s.DisplayOrder)){
			<tr>
				<td>
					@Category.Name
				</td>
				<td>
					@Category.DisplayOrder
				</td>
				<td>
					<div class="w-75 btn-group" role="group">
							<a asp-controller="Category" asp-action="Edit" asp-route-id="@Category.ID" class="btn btn-primary mx-2">
								<i class="bi bi-pencil-square"></i>Edit
						</a>
						<a asp-controller="Category" asp-action="Delete" asp-route-id="@Category.ID" class="btn btn-danger mx-2">
								<i class="bi bi-trash-fill"></i>Delete
						</a>
					</div>
				</td>
			</tr>
		}
	</tbody>
</table>
</div>

BookStore/Areas/Admin/Views/Category/Update.cshtml
@model Category
<div class="card shadow border-0 mt-4">
	<div class="cardaccordion-header bg-secondary bg-gradient m-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Create Category</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<form method="post">

			<div class=" border p-3 ">
				
				<div class="form-floating py-2 col-12">
					<input asp-for="Name" class="form-control border-0 shadow" />
					<label asp-for="Name" class="ms-2">Category Name</label>

					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="DisplayOrder" class="form-control border-0 shadow" />
					<label asp-for="DisplayOrder" class="ms-2"></label>

					<span asp-validation-for="DisplayOrder" class="ms-2"></span>
				</div>
				<div class="row pt-2">
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-success form-control">Create</button>
					</div>
					<div class="col-6  col-md-3">
						<a asp-controller="Products" asp-action="Index" class="btn btn-danger  form-control">Back to Category List</a>
					</div>
				</div>

			</div>

		</form>
	</div>
</div>

		



@section Scripts{
	

	@{
		<partial name="_ValidationScriptsPartial"></partial>
	}
}