BookStore/Areas/Admin/Controllers/CategoryController.cs
using DataAccess.Data;
using DataAccess.Repository;
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models.Entites;
using Utilites;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles =StaticDetails.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _UnitOfWork = unitOfWork;

        }
        public IActionResult Index()
        {
            List<Category> categories = _UnitOfWork.Category.GetAll().ToList();
            return View(categories);
        }
        public IActionResult Create()
        {
            return View();

        }

        [HttpPost]
        public IActionResult Create(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "Category Name and Display Order Cannot be exactly same");
            }
            if (ModelState.IsValid)
            {
                TempData["Success"] = "Category Created Succeccfully";
                _UnitOfWork.Category.Add(obj);
                _UnitOfWork.Save();
            }
            return RedirectToAction("Index");

        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? CategoryFromDb = _UnitOfWork.Category.Get(temp => temp.ID == id);
            if (CategoryFromDb == null)
            {
                return NotFound();
            }
            return View(CategoryFromDb);
        }
        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _UnitOfWork.Category.Update(category);
                _UnitOfWork.Save();
                TempData["Success"] = "Category Edited Succeccfully";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? CategoryFromDb = _UnitOfWork.Category.Get(temp => temp.ID == id);
            if (CategoryFromDb == null)
            {
                return NotFound();
            }
            return View(CategoryFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Category? obj = _UnitOfWork.Category.Get(temp => temp.ID == id);
            if (obj == null)
            {
                return NotFound();
            }

            _UnitOfWork.Category.Delete(obj);
            _UnitOfWork.Save();
            TempData["Success"] = "Category Deleted Succeccfully";
            return RedirectToAction("index");
        }
    }
}

BookStore/Areas/Admin/Controllers/CompanyController.cs
using DataAccess.Repository;
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.FileProviders;
using Models.Entites;
using Models.ViewModels;
using Utilites;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        
        public CompanyController(IUnitOfWork unitOfWork)
        {
            _UnitOfWork = unitOfWork;
            
        }
        public IActionResult Index()
        {
            List<Company> ComapnyList = _UnitOfWork.Company.GetAll().ToList();
            return View(ComapnyList);
        }
        public IActionResult Upsert(int? id)
        {
              

            if (id == null||id==0)
            {
                return View(new Company());
            }
            else
            {
             Company  company = _UnitOfWork.Company.Get(temp => temp.ID == id);
                return View(company);
            }
            
        }

        [HttpPost]
        public IActionResult Upsert(Company company)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (company.ID==0)
            {
                TempData["Success"] = "Company Added Succeccfully";
                _UnitOfWork.Company.Add(company);
            }
            else
            {
                TempData["Success"] = "Company Updated Succeccfully";
                _UnitOfWork.Company.Update(company);
            }

            _UnitOfWork.Save();
            return RedirectToAction("Index");

        }



        //public IActionResult Delete(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }
        //    Product? obj = _UnitOfWork.Product.Get(temp => temp.ID == id);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(obj);
        //}
        //[HttpPost, ActionName("Delete")]
        //public IActionResult DeleteProduct(int? id)
        //{
        //    Product? obj = _UnitOfWork.Product.Get(temp => temp.ID == id);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }
        //    _UnitOfWork.Product.Delete(obj);
        //    _UnitOfWork.Save();
        //    TempData["Success"] = "Category Deleted Succeccfully";
        //    return RedirectToAction("Index");
        //}
        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            var ComapnyList=_UnitOfWork.Company.GetAll();
            return Json(new { data = ComapnyList });
        }
       
        public IActionResult Delete(int? id)
        {
            var CompanyToDelete = _UnitOfWork.Company.Get(temp=>temp.ID==id);
            if (CompanyToDelete == null)
            {
                return Json(new { success = false, message = "Error While Deleting" });
            }
           
            _UnitOfWork.Company.Delete(CompanyToDelete);
            _UnitOfWork.Save();
            return Json(new { success=true, message="Delete Successful" });
        }

        #endregion
    }
}

BookStore/Areas/Admin/Controllers/OrderController.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Models.Entites;
using Models.identityEntites;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        public OrderController(IUnitOfWork unitOfWork)
        {
            _UnitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            
            return View();
        }

        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            List<OrderHeader> OrderList = _UnitOfWork.OrderHeader.GetAll(includeProperties: nameof(ApplicationUser)).ToList();
            return Json(new { data = OrderList });
        }

       

        #endregion
    }
}

BookStore/Areas/Customer/Controllers/CartController.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using Models.Entites;
using Models.identityEntites;
using Models.ViewModels;
using Stripe.Checkout;
using System.Security.Claims;
using Utilites;

namespace BookStore.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public ShoppingCartVM ShoppingCartVM { get; set; }
        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;

        }
        public IActionResult Index()
        {
            var ClaimsIdentity = (ClaimsIdentity)User.Identity;
            var UserID = ClaimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            ShoppingCartVM = new ShoppingCartVM
            {
                ListCart = _unitOfWork.ShoppingCart.GetAll(temp => temp.ApplicationUserID == UserID, nameof(ShoppingCart.product)),
                OrderHeader=new()
                
            };

            foreach (var cart in ShoppingCartVM.ListCart)
            {
                cart.Price = GetPriceBasedOnQuantity(cart);
                ShoppingCartVM.OrderHeader.OrderTotal += cart.Price * cart.Count;
            }
            return View(ShoppingCartVM);
        }

        public IActionResult Plus(int CartID)
        {
            var Cart = _unitOfWork.ShoppingCart.Get(temp => temp.ID == CartID);
            Cart.Count++;
            _unitOfWork.ShoppingCart.Update(Cart);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Minus(int CartID)
        {
            var Cart = _unitOfWork.ShoppingCart.Get(temp => temp.ID == CartID);
            if (Cart.Count <= 1)
            {
                _unitOfWork.ShoppingCart.Delete(Cart);
            }
            else
            {
                Cart.Count--;
                _unitOfWork.ShoppingCart.Update(Cart);
            }
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Remove(int CartID)
        {
            var Cart = _unitOfWork.ShoppingCart.Get(temp => temp.ID == CartID);
            _unitOfWork.ShoppingCart.Delete(Cart);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Summary()
        {
            var ClaimsIdentity = (ClaimsIdentity)User.Identity;
            var UserID = ClaimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            ShoppingCartVM = new ShoppingCartVM
            {
                ListCart = _unitOfWork.ShoppingCart.GetAll(temp => temp.ApplicationUserID == UserID, nameof(ShoppingCart.product)),
                OrderHeader = new()

            };
            ShoppingCartVM.OrderHeader.ApplicationUser = _unitOfWork.applicationUser.Get(x => x.Id == UserID);
            ShoppingCartVM.OrderHeader.Name = ShoppingCartVM.OrderHeader.ApplicationUser.Name;
            ShoppingCartVM.OrderHeader.City = ShoppingCartVM.OrderHeader.ApplicationUser.City;
            ShoppingCartVM.OrderHeader.PostalCode = ShoppingCartVM.OrderHeader.ApplicationUser.PostalCode;
            ShoppingCartVM.OrderHeader.State = ShoppingCartVM.OrderHeader.ApplicationUser.State;
            ShoppingCartVM.OrderHeader.PhoneNumber = ShoppingCartVM.OrderHeader.ApplicationUser.PhoneNumber;
            ShoppingCartVM.OrderHeader.StreetAddress = ShoppingCartVM.OrderHeader.ApplicationUser.StreetAddress;


            foreach (var cart in ShoppingCartVM.ListCart)
            {
                cart.Price = GetPriceBasedOnQuantity(cart);
                ShoppingCartVM.OrderHeader.OrderTotal += cart.Price * cart.Count;
            }
            return View(ShoppingCartVM);
        }

        [HttpPost]
        [ActionName("Summary")]
        public IActionResult SummaryPost()
        {
            var ClaimsIdentity = (ClaimsIdentity)User.Identity;
            var UserID = ClaimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            ShoppingCartVM.ListCart = _unitOfWork.ShoppingCart.GetAll(temp => temp.ApplicationUserID == UserID, nameof(ShoppingCart.product));
              

             ShoppingCartVM.OrderHeader.OrderDate=System.DateTime.Now;
             ShoppingCartVM.OrderHeader.ApplicationUserID=UserID;

            ApplicationUser applicationUser = _unitOfWork.applicationUser.Get(x => x.Id == UserID);
            

            foreach (var cart in ShoppingCartVM.ListCart)
            {
                cart.Price = GetPriceBasedOnQuantity(cart);
                ShoppingCartVM.OrderHeader.OrderTotal += cart.Price * cart.Count;
            }

            if (applicationUser.CompanyID.GetValueOrDefault() == 0)
            {
                //Customer is placing an Order
                ShoppingCartVM.OrderHeader.OrderStatus = StaticDetails.StatusPending;
                ShoppingCartVM.OrderHeader.PaymentStatus = StaticDetails.PaymentStatusPending;
            }
            else
            {
                //company is placing an Order
                ShoppingCartVM.OrderHeader.OrderStatus = StaticDetails.StatusApproved;
                ShoppingCartVM.OrderHeader.PaymentStatus = StaticDetails.PaymentStatusDelayedPayment;
            }
                _unitOfWork.OrderHeader.Add(ShoppingCartVM.OrderHeader);
                _unitOfWork.Save();
            foreach(var cart in ShoppingCartVM.ListCart)
            {
                OrderDetail orderDetail = new OrderDetail
                {
                    ProductID = cart.ProductID,
                    OrderHeaderID = ShoppingCartVM.OrderHeader.ID,
                    Price=cart.Price,
                    Count=cart.Count
                };
                _unitOfWork.OrderDetail.Add(orderDetail);
                _unitOfWork.Save();
            }
            if (applicationUser.CompanyID.GetValueOrDefault() == 0)
            {
                var domain = "https://localhost:7293/";
                //stripe logic
                var options = new Stripe.Checkout.SessionCreateOptions
                {

                    SuccessUrl = domain + $"customer/cart/OrderConfirmation?id={ShoppingCartVM.OrderHeader.ID}",
                    CancelUrl = domain + "customer/cart/index",
                    LineItems = new List<Stripe.Checkout.SessionLineItemOptions>(),
                    Mode = "payment",
                };

                foreach(var item in ShoppingCartVM.ListCart)
                {
                    var SessionLineItem = new SessionLineItemOptions()
                    {
                        PriceData = new SessionLineItemPriceDataOptions()
                        {
                            UnitAmount = (long)(item.Price * 100),
                            Currency = "usd",
                            ProductData = new SessionLineItemPriceDataProductDataOptions
                            {
                                Name = item.product.Title,

                            }
                        },
                        Quantity = item.Count

                    };
                    options.LineItems.Add(SessionLineItem);
                    
                }
                var service = new Stripe.Checkout.SessionService();
               Session session  = service.Create(options);
                _unitOfWork.OrderHeader.UpdateStribePaymentID(ShoppingCartVM.OrderHeader.ID, session.Id, session.PaymentIntentId);
                _unitOfWork.Save();
                Response.Headers.Add("Location", session.Url);
                return new StatusCodeResult(303);
            }
            return RedirectToAction("Confirmation");
        }
        public IActionResult OrderConfirmation(int id)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.Get(temp => temp.ID == id);
            var Service = new SessionService();
            Session session = Service.Get(orderHeader.SesssionID);
            _unitOfWork.OrderHeader.UpdateStauts(id, StaticDetails.StatusApproved,StaticDetails.PaymentStatusApproved);
          List< ShoppingCart> shoppingCart = _unitOfWork.ShoppingCart.GetAll(temp => temp.ApplicationUserID == orderHeader.ApplicationUserID).ToList();
            _unitOfWork.ShoppingCart.DeleteRange(shoppingCart);
            _unitOfWork.Save();
            return View(id);
        }
        public double GetPriceBasedOnQuantity(ShoppingCart cart)
        {

            if (cart.Count <= 50)
            {
                return cart.product.Price;
            }
            else if (cart.Count <= 100)
            {
                return cart.product.Price50;
            }
            else
            {
                return cart.product.Price100;
            }
        }
    }
}

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookStore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css"/>
    <link rel="stylesheet" href="//cdn.datatables.net/2.2.1/css/dataTables.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto>
                        <li class="nav-item">
                        <a class="nav-link  " asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Orders</a>
                        </li>
                        @* @if (User.IsInRole(StaticDetails.Role_Admin)) *@
                        @* { *@
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Mangement
                            </a>
                        <ul class="dropdown-menu">
                            <li class="nav-item">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                            <li><hr class="dropdown-divider"></li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Companies</a>
                                </li>
                        </ul>
                        </li>
                       
                        @* } *@
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-cart"></i>&nbsp;
                            </a>
                        </li>
                    </ul>
                    
                    
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top bg-primary footer  text-light">
        <div class="container" >
            &copy; 2025 - BookStore  <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.2.1/js/dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/0k8lwofr7kvutdaijqo2xwyjypic6z4r1bwp1vxiiqgw6hqm/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookStore/Views/Shared/_Notification.cshtml
@if(TempData["Success"]!=null){
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">toastr.success("@TempData["Success"]");</script>
} 